version: "3"

services:
    db:
        image: postgres:16-alpine
        environment:
            LANG: fr_FR.utf8
            POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=fr-FR
            POSTGRES_PASSWORD: toto
            POSTGRES_DB: matchroom-db
        volumes:
            - .:/sql
            - db:/var/lib/postgresql/data
        ports:
            - 6500:5432

    adminer:
        image: adminer:latest
        ports:
            - 8083:8080
        depends_on:
            - db

volumes:
    db:
